  spring:
    application:
      name: sahyadri-bconnect-backend

    ai:
      mcp:
        server:
          protocol: STREAMABLE

  server:
    port: 8080

  logging:
    level:
      root: INFO
      com.sbc: DEBUG
